// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendExam.Models;

public partial class MyOfficeAcpdDTO
{
    public string ACPD_SID { get; set; }

    public string ACPD_CNAME { get; set; }

    public string ACPD_ENAME { get; set; }

    public string ACPD_SNAME { get; set; }

    public string ACPD_EMAIL { get; set; }

    public byte? ACPD_STATUS { get; set; }

    public bool? ACPD_STOP { get; set; }

    public string ACPD_STOP_MEMO { get; set; }

    public string ACPD_LOGIN_ID { get; set; }

    public string ACPD_LOGIN_PWD { get; set; }

    public string ACPD_MEMO { get; set; }

    public DateTime? ACPD_NOWDATETIME { get; set; }

    public string ACPD_NOWID { get; set; }

    public DateTime? ACPD_UPDDATETIME { get; set; }

    public string ACPD_UPDID { get; set; }

}