// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BackendExam.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BackendExam.Models
{
    public partial interface IBackendExamHubContextProcedures
    {
        Task<int> NEWSIDAsync(string TableName, OutputParameter<string> ReturnSID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_AddLogAsync(byte? _InBox_ReadID, string _InBox_SPNAME, Guid? _InBox_GroupID, string _InBox_ExProgram, string _InBox_ActionJSON, OutputParameter<string> _OutBox_ReturnValues, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_AddMyoffice_ACPDResult>> usp_AddMyoffice_ACPDAsync(string JsonData, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_DeleteMyoffice_ACPDAsync(string ACPD_SID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_GetMyoffice_ACPDResult>> usp_GetMyoffice_ACPDAsync(string ACPD_SID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_UpdateMyoffice_ACPDAsync(string JsonData, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
