// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BackendExam.Models
{
    public partial class usp_AddMyoffice_ACPDResult
    {
        public string JsonResult { get; set; }
    }
}
